# Nombre de la aplicación
spring.application.name=RapidosyFuriosos

# Definir el puerto con el cual se accederá a la aplicación
server.port=8089

# URL del proyecto
server.servlet.context-path=/rapidosyfuriosos

# Cadena de conexión
spring.datasource.url=jdbc:mysql://localhost:3306/bdrapidosyfuriosos20262

# Usuario de la bd
spring.datasource.username=root

# Password de la db
spring.datasource.password=admin123

# Driver de MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
